{
 "title": "Fritz!Box Docsis Statistics",
 "time": { "from": "now-24h", "to": "now" },
 "refresh": "10s",
 "panels": [
  {
   "title": "Docsis Quality",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 0 },
   "targets": [
    {}
   ]
  },
  {
   "title": "Upstream Power Level",
   "type": "timeseries",
   "gridPos": { "h": 7, "w": 24, "x": 0, "y": 1 },
   "fieldConfig": { "defaults": { "unit": "dBmV" } },
   "targets": [
    {
     "expr": "fritz_channel_power_level{direction=\"upstream\"}",
     "legendFormat": "{{frequency}} MHz ({{docsisVersion}})"
    }
   ]
  },
  {
   "title": "Downstream MSE",
   "type": "timeseries",
   "description": "MSE = Median Squared Errors",
   "gridPos": { "h": 8, "w": 24, "x": 0, "y": 8 },
   "fieldConfig": { "defaults": { "unit": "dB" } },
   "targets": [
    {
     "expr": "fritz_channel_mse{docsisVersion=\"3.0\",direction=\"downstream\"}",
     "legendFormat": "{{frequency}} MHz"
    }
   ]
  },
  {
   "title": "Downstream Power Level",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 24, "x": 0, "y": 16 },
   "fieldConfig": { "defaults": { "unit": "dBmV" } },
   "targets": [
    {
     "expr": "fritz_channel_power_level{direction=\"downstream\"}",
     "legendFormat": "{{frequency}} MHz ({{docsisVersion}})"
    }
   ]
  },
  {
   "title": "Non-Correctable Channel Errors (Delta)",
   "type": "timeseries",
   "description": "Docsis 3.0 only",
   "gridPos": { "h": 8, "w": 24, "x": 0, "y": 24 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "targets": [
    {
     "expr": "irate(fritz_channel_uncorrectable_errors[1m])",
     "legendFormat": "{{frequency}} MHz"
    }
   ]
  },
  {
   "title": "Docsis Details",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 32 },
   "targets": [
    {}
   ]
  },
  {
   "title": "Correctable Channel Errors (Rate)",
   "type": "timeseries",
   "description": "Docsis 3.0 only",
   "gridPos": { "h": 6, "w": 24, "x": 0, "y": 33 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "targets": [
    {
     "expr": "irate(fritz_channel_correctable_errors[1m])",
     "legendFormat": "{{frequency}} MHz"
    }
   ]
  },
  {
   "title": "Upstream Connection Type (QAM)",
   "type": "stat",
   "gridPos": { "h": 5, "w": 24, "x": 0, "y": 39 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "fritz_channel_connection_type{docsisVersion=\"3.0\"}",
     "legendFormat": "{{frequency}} MHz"
    }
   ]
  },
  {
   "title": "Upstream Connection Type (QAM)",
   "type": "timeseries",
   "gridPos": { "h": 5, "w": 12, "x": 0, "y": 44 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "targets": [
    {
     "expr": "fritz_channel_connection_type{direction=\"upstream\"}",
     "legendFormat": "{{frequency}} MHz"
    }
   ]
  },
  {
   "title": "Downstream Connection Type (QAM)",
   "type": "timeseries",
   "gridPos": { "h": 5, "w": 12, "x": 12, "y": 44 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "targets": [
    {
     "expr": "fritz_channel_connection_type{direction=\"downstream\"}",
     "legendFormat": "{{frequency}} MHz"
    }
   ]
  }
 ]
}