apiVersion: v1
kind: Service
metadata:
  name: fritz-docsis
  namespace: monitoring
  annotations:
    prometheus.io/scrape: "true"
spec:
  type: NodePort
  ports:
  - port: 9100
    targetPort: 2112
  selector:
    app: fritz-docsis
