{
 "title": "FritzBox Docsis Statistiks",
 "time": { "from": "now-15m", "to": "now" },
 "refresh": "30s",
 "panels": [
  { "title": "Upstream", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 0 } },
  {
   "title": "Channel Power Level",
   "type": "graph",
   "gridPos": { "h": 11, "w": 24, "x": 0, "y": 1 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "fritz_channel_power_level{direction=\"upstream\"}",
     "legendFormat": "ChannelID {{channelID}}"
    }
   ]
  },
  {
   "title": "Channel Connection Type (QAM)",
   "type": "graph",
   "gridPos": { "h": 9, "w": 24, "x": 0, "y": 12 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "fritz_channel_connection_type{direction=\"upstream\"}",
     "legendFormat": "ChannelID {{channelID}}"
    }
   ]
  },
  { "title": "Downstream", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 21 } },
  {
   "title": "Correctable Channel Errors (Rate)",
   "type": "graph",
   "description": "Docsis 3.0 only",
   "gridPos": { "h": 9, "w": 24, "x": 0, "y": 22 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "irate(fritz_channel_correctable_errors[1m])",
     "legendFormat": "ChannelID {{channelID}}"
    }
   ]
  },
  {
   "title": "UN-Correctable Channel Errors (Rate)",
   "type": "graph",
   "description": "Docsis 3.0 only",
   "gridPos": { "h": 9, "w": 24, "x": 0, "y": 31 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "irate(fritz_channel_uncorrectable_errors[1m])",
     "legendFormat": "ChannelID {{channelID}}"
    }
   ]
  },
  {
   "title": "Channel MSE",
   "type": "graph",
   "description": "MSE = Median Squared Errors",
   "gridPos": { "h": 16, "w": 24, "x": 0, "y": 40 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "fritz_channel_mse{direction=\"downstream\"}",
     "legendFormat": "ChannelID {{channelID}} Docsis {{docsisVersion}}"
    }
   ]
  },
  {
   "title": "Channel Power Level",
   "type": "graph",
   "gridPos": { "h": 16, "w": 24, "x": 0, "y": 56 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "fritz_channel_power_level{direction=\"downstream\"}",
     "legendFormat": "ChannelID {{channelID}} Docsis {{docsisVersion}}"
    }
   ]
  },
  {
   "title": "Channel Connection Type (QAM)",
   "type": "graph",
   "gridPos": { "h": 9, "w": 24, "x": 0, "y": 72 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "fritz_channel_connection_type{direction=\"downstream\"}",
     "legendFormat": "ChannelID {{channelID}}"
    }
   ]
  }
 ]
}